name: Deploy on Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 20.15.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.15.0

      - name: Install packages
        run: yarn

      - name: Run tests
        run: yarn test:cov
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Install Railway
        run: yarn add -g @railway/cli

      - name: Deploy
        run: railway up --service plunge-backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}