name: Merge Branch

on:
  workflow_dispatch:
    inputs:
      origin:
        description: 'Origin branch'
        required: true
        default: 'dev'
      destination:
        description: 'Destination branch'
        required: true
        default: 'main'

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --global user.name ${{ secrets.OWNER_GITHUB_USER_NAME }}
        git config --global user.email ${{ secrets.OWNER_GITHUB_EMAIL }}

    - name: Merge Branch
      run: |
        git fetch origin
        git checkout ${{ github.event.inputs.destination }}
        git merge origin/${{ github.event.inputs.origin }}
        git push origin ${{ github.event.inputs.destination }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
