name: Manual Merge Development to Main

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to merge into'
        required: true
        default: 'main'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "Jhones Jhonatas"
          git config user.email "jhones.jhonatas@outlook.com.br"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout target branch
        run: git checkout ${{ github.event.inputs.target_branch }}

      - name: Merge development into target branch
        run: |
          git merge development --no-ff -m "Merge branch 'development' into ${{ github.event.inputs.target_branch }}"
          git push origin ${{ github.event.inputs.target_branch }}
