name: Manual Merge Development to Main

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to merge into'
        required: true
        default: 'main'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Checkout development branch
        run: git checkout development

      - name: Merge development into main
        run: |
          git merge development
          git push origin ${{ github.event.inputs.target_branch }}
