name: Manual Merge Development

on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        description: 'Mensagem de commit para a mesclagem (opcional)'

env:
  MERGE_MESSAGE: ${{ github.event.inputs.message || 'Merge development' }}

jobs:
  merge-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch branch 'development'
        run: |
          git fetch origin development

      - name: Merge branch 'development' into 'main'
        run: |
          git checkout development
          git pull origin development --allow-unrelated-histories
          git checkout main
          git merge --no-ff development --allow-unrelated-histories
          git push origin main -m "$MERGE_MESSAGE"

